sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t highjune37/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true highjune37/docker-react-app npm run test -- --coverage

after_succes:
  - echo "Test success"